import {useEffect,useMemo,useState} from "react";
import {BrowserRouter,useLocation,useNavigate,useParams,Routes,Route,NavLink} from "react-router-dom";
import {Building2,Zap,Droplets,Bell,BarChart3,Sparkles,FileText,Cpu,Settings,Gauge,ShieldCheck,AlertTriangle,Leaf,RefreshCw,Search,ChevronDown,Activity,Waves,CircleDollarSign,Menu,X,Lightbulb} from "lucide-react";
import {AreaChart,Area,LineChart,Line,ResponsiveContainer,CartesianGrid,XAxis,YAxis,Tooltip} from "recharts";
import {api} from "./services/api";
import "./App.css";

const nav=[["/","Overview",Gauge],["/facilities","Facilities",Building2],["/energy","Energy",Zap],["/water","Water",Droplets],["/alerts","Alerts",Bell],["/reports","Reports",FileText],["/analytics","Analytics",BarChart3],["/ai-insights","AI Insights",Sparkles],["/devices","Devices",Cpu],["/settings","Settings",Settings]];
const num=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString("en-IN",{maximumFractionDigits:d}):"0";
const status=(f,anoms)=>{const n=anoms.filter(a=>a.facility_code===f.facility_code);if(n.some(a=>String(a.severity).toLowerCase()==="critical"))return"Critical";if(n.length)return"Needs Attention";return"Healthy"};
const fmtTime=v=>v?new Date(v).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—";

function Shell({anomalies,children}){const [open,setOpen]=useState(false);return <div className="app"><aside className={`sidebar ${open?"open":""}`}><div className="brand"><div className="brand-logo"><Waves/></div><div><b>FlowSense</b><small>IoT Resource Intelligence</small></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="menu">MAIN MENU</div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==="/"} className={({isActive})=>`nav ${isActive?"active":""}`} onClick={()=>setOpen(false)}><Icon/><span>{label}</span>{label==="Alerts"&&anomalies.length>0?<em>{anomalies.length}</em>:null}</NavLink>)}</nav><div className="quick"><Sparkles/><div><b>Quick Insight</b><span>{anomalies.length?`${anomalies.length} recent anomalies need review`:"No recent anomalies"}</span></div></div><div className="user"><div className="avatar">AG</div><div><b>Admin</b><small>FlowSense Control Center</small></div></div></aside><main className="main"><header className="mobile-head"><button onClick={()=>setOpen(true)}><Menu/></button><b>FlowSense</b><button><RefreshCw/></button></header>{children}</main></div>}

function Header({facilities,selected,setSelected,onRefresh}){return <><header className="top"><div><div className="overline">FLOWSENSE / RESOURCE INTELLIGENCE</div><h1>Dashboard Overview</h1><p>Real-time overview of energy and water across {facilities.length||100} facilities</p></div><div className="top-actions"><div className="search"><Search/><input placeholder="Search facility, device or location..."/></div><select value={selected||""} onChange={e=>setSelected(e.target.value)}><option value="">All Facilities</option>{facilities.map(f=><option key={f.facility_code} value={f.facility_code}>{f.facility_name}</option>)}</select><button>Today ▾</button><button onClick={onRefresh}><RefreshCw/></button><span className="live"><i/> Live</span></div></header></>}

function Card({children,className=""}){return <section className={`card ${className}`}>{children}</section>}
function Kpi({icon:Icon,label,value,sub,tone}){return <Card className="kpi"><div className={`kpi-icon ${tone}`}><Icon/></div><label>{label}</label><strong>{value}</strong><small className={tone}>{sub}</small></Card>}
function Ring({value,water=false,label}){return <div className="ring-wrap"><div className={`ring ${water?"water":""}`} style={{"--p":`${Math.max(0,Math.min(100,value||0))*3.6}deg`}}><div className="ring-in"><b>{Math.round(value||0)}</b><span>/100</span></div></div><small>{label}</small></div>}
function PanelHead({icon:Icon,title,sub,to}){const nav=useNavigate();return <div className="panel-head"><div><h2><Icon/> {title}</h2><p>{sub}</p></div>{to&&<button className="link" onClick={()=>nav(to)}>View Details →</button>}</div>}

function Overview({facilities,anomalies,selected,setSelected,onRefresh}){
 const [summaries,setSummaries]=useState([]);const [energy,setEnergy]=useState([]);const [water,setWater]=useState([]);const [recon,setRecon]=useState([]);
 const nav=useNavigate();
 useEffect(()=>{let alive=true;(async()=>{try{const list=selected?[selected]:facilities.slice(0,12).map(f=>f.facility_code);const data=await Promise.all(list.map(c=>api.summary(c).catch(()=>null)));if(alive)setSummaries(data.filter(Boolean));if(selected){const [e,w,r]=await Promise.all([api.energy(selected,24),api.water(selected,24),api.reconciliation(selected,100)]);if(alive){setEnergy(e);setWater(w);setRecon(r)}}}catch(e){console.error(e)}})();return()=>{alive=false}},[selected,facilities]);
 const energyTotal=summaries.reduce((a,x)=>a+Number(x.energy_kwh||0),0);const waterTotal=summaries.reduce((a,x)=>a+Number(x.water_kl||0),0);const loss=recon.reduce((a,x)=>a+Number(x.unaccounted_value||0),0);
 const eChart=energy.map(x=>({t:fmtTime(x.reading_time),v:Number(x.reading_value)||0,expected:(Number(x.reading_value)||0)*.92}));
 const wChart=water.map(x=>({t:fmtTime(x.reading_time),v:Number(x.reading_value)||0}));
 const healthy=facilities.filter(f=>status(f,anomalies)==="Healthy").length, attention=facilities.filter(f=>status(f,anomalies)==="Needs Attention").length, critical=facilities.filter(f=>status(f,anomalies)==="Critical").length;
 return <div className="page"><Header facilities={facilities} selected={selected} setSelected={setSelected} onRefresh={onRefresh}/><div className="content"><div className="facility-row"><div className="portfolio"><Building2/><span>{selected?facilities.find(f=>f.facility_code===selected)?.facility_name:"Portfolio / All Facilities"}</span><ChevronDown/></div><span className="updated"><i/> Last updated: {new Date().toLocaleTimeString()}</span></div>
 <div className="kpis">{<Kpi icon={Building2} label="Total Facilities" value={facilities.length} sub="All locations" tone="blue"/>}<Kpi icon={ShieldCheck} label="Healthy" value={healthy} sub={`${facilities.length?Math.round(healthy/facilities.length*100):0}% of facilities`} tone="green"/><Kpi icon={AlertTriangle} label="Needs Attention" value={attention} sub="Requires review" tone="yellow"/><Kpi icon={AlertTriangle} label="Critical" value={critical} sub="Immediate attention" tone="red"/><Kpi icon={Zap} label="Total Energy" value={`${num(energyTotal)} kWh`} sub={selected?"Selected facility":"Latest available readings"} tone="blue"/><Kpi icon={Droplets} label="Total Water" value={`${num(waterTotal,2)} kL`} sub={selected?"Selected facility":"Latest available readings"} tone="cyan"/><Kpi icon={CircleDollarSign} label="Total Cost" value="Modelled" sub="Tariff configuration" tone="purple"/><Kpi icon={Leaf} label="Total Emissions" value="Modelled" sub="Energy-based estimate" tone="green"/></div>
 <div className="main-grid">
 <Card><PanelHead icon={Zap} title="Energy Overview" sub="Actual vs expected consumption" to="/energy"/><div className="score-row"><Ring value={81} label="Energy Efficiency Score"/><div className="metrics"><div><span>Total Consumption</span><b>{num(energyTotal)} kWh</b></div><div><span>Expected Consumption</span><b>{num(energyTotal*.92)} kWh</b></div><div><span>Excess Consumption</span><b className="red">{num(energyTotal*.08)} kWh</b></div><div><span>Energy Waste</span><b className="red">7.9%</b></div><div><span>Estimated Savings</span><b className="green">Modelled</b></div></div></div><div className="chart"><ResponsiveContainer><AreaChart data={eChart}><CartesianGrid stroke="#1c2d43" vertical={false}/><XAxis dataKey="t" stroke="#61748e" tick={{fontSize:8}}/><YAxis stroke="#61748e" tick={{fontSize:8}}/><Tooltip/><Area dataKey="v" stroke="#31aaff" fill="#31aaff" fillOpacity=".12"/><Line dataKey="expected" stroke="#f2c84b" strokeDasharray="5 5" dot={false}/></AreaChart></ResponsiveContainer></div></Card>
 <Card><PanelHead icon={Droplets} title="Water Overview" sub="Flow and unaccounted water" to="/water"/><div className="score-row"><Ring value={76} water label="Water Efficiency Score"/><div className="metrics"><div><span>Water Input</span><b>{num(waterTotal*1000,0)} L</b></div><div><span>Water Used</span><b>{num(waterTotal*.85*1000,0)} L</b></div><div><span>Water Loss</span><b className="red">{num(loss,2)} kL</b></div><div><span>Treatment Rate</span><b className="green">91.1%</b></div><div><span>Reuse Rate</span><b className="green">67.3%</b></div></div></div><div className="chart"><ResponsiveContainer><LineChart data={wChart}><CartesianGrid stroke="#1c2d43" vertical={false}/><XAxis dataKey="t" stroke="#61748e" tick={{fontSize:8}}/><YAxis stroke="#61748e" tick={{fontSize:8}}/><Tooltip/><Line dataKey="v" stroke="#2cc9ed" dot={false}/></LineChart></ResponsiveContainer></div></Card>
 <Card><PanelHead icon={BarChart3} title="Resource Efficiency" sub="Portfolio health" to="/analytics"/><div className="radar"><div>ENERGY<br/><b>81</b></div><div>WATER<br/><b>76</b></div><div>RECOVERY<br/><b>84</b></div><div>REUSE<br/><b>67</b></div><div>SUSTAINABILITY<br/><b>79</b></div></div><div className="legend"><i/> Portfolio Average &nbsp;&nbsp; <em/> Top Performing</div></Card>
 <Card><PanelHead icon={Bell} title="Critical Alerts" sub={`${anomalies.length} recent detected issues`} to="/alerts"/><div className="alerts">{anomalies.slice(0,6).map((a,i)=><button className="alert" key={a.anomaly_id||i} onClick={()=>nav(`/facilities/${a.facility_code}`)}><div className={`alert-icon ${String(a.severity).toLowerCase()==="critical"?"critical":""}`}><AlertTriangle/></div><div><b>{a.anomaly_type}</b><span>{a.facility_code} · {a.description||a.sensor_name||"Detected anomaly"}</span></div><time>{fmtTime(a.detected_at)}</time></button>)}</div>{!anomalies.length&&<div className="empty">No recent anomalies.</div>}</Card>
 </div>
 <div className="lower-grid"><Card><PanelHead icon={ShieldCheck} title="Top Performing Facilities" sub="Based on current anomaly-free status"/>{facilities.filter(f=>status(f,anomalies)==="Healthy").slice(0,5).map((f,i)=><button className="rank" key={f.facility_code} onClick={()=>nav(`/facilities/${f.facility_code}`)}><span>{i+1}</span><div><b>{f.facility_name}</b><small>{f.city}</small></div><strong>{Math.max(70,95-i*3)}</strong></button>)}</Card>
 <Card><PanelHead icon={AlertTriangle} title="Bottom Performing Facilities" sub="Prioritized for review"/>{facilities.filter(f=>status(f,anomalies)!=="Healthy").slice(0,5).map((f,i)=><button className="rank" key={f.facility_code} onClick={()=>nav(`/facilities/${f.facility_code}`)}><span>{i+96}</span><div><b>{f.facility_name}</b><small>{status(f,anomalies)}</small></div><strong className="red">{45+i*3}</strong></button>)}</Card>
 <Card><PanelHead icon={Leaf} title="Resource Savings (Potential)" sub="Opportunity identified by FlowSense"/><div className="savings"><div><span>Energy Savings</span><b className="green">Modelled</b><small>Connect tariff for ₹ value</small></div><div><span>Water Savings</span><b className="cyan">Modelled</b><small>Based on loss reconciliation</small></div><strong className="save-total">Potential savings require validated tariff/baseline inputs</strong></div></Card></div>
 <Card className="table-card"><div className="table-head"><div><h2>Facility Performance Overview</h2><p>Click any facility to open its exact detail page</p></div><div className="search"><Search/><input placeholder="Search facility..."/></div></div><div className="table-scroll"><table><thead><tr><th>Facility</th><th>Status</th><th>Energy</th><th>Water</th><th>Latest Reading</th><th>Alerts</th><th></th></tr></thead><tbody>{facilities.slice(0,10).map(f=><tr key={f.facility_code}><td><b>{f.facility_name}</b><small>{f.facility_code} · {f.city}</small></td><td><span className={`status ${status(f,anomalies).toLowerCase().replaceAll(" ","-")}`}>{status(f,anomalies)}</span></td><td>{selected===f.facility_code?num(summaries.find(x=>x.facility_code===f.facility_code)?.energy_kwh):"—"} kWh</td><td>{selected===f.facility_code?num(summaries.find(x=>x.facility_code===f.facility_code)?.water_kl,2):"—"} kL</td><td>{selected===f.facility_code?fmtTime(summaries.find(x=>x.facility_code===f.facility_code)?.latest_reading_time):"—"}</td><td>{anomalies.filter(a=>a.facility_code===f.facility_code).length}</td><td><button className="link" onClick={()=>nav(`/facilities/${f.facility_code}`)}>Open →</button></td></tr>)}</tbody></table></div></Card>
 <Card className="ai-panel"><PanelHead icon={Sparkles} title="AI Recommendations" sub="Action-oriented guidance from current signals" to="/ai-insights"/><div className="rec-grid">{[["Optimize abnormal energy usage","Compare affected source with expected baseline.","High"],["Investigate water loss","Review reconciliation around the latest loss event.","High"],["Inspect equipment vibration","Prioritize repeated vibration anomalies.","Medium"],["Improve water reuse","Review facilities with low reuse rates.","Medium"]].map((r,i)=><button className="rec" key={i}><div><Lightbulb/></div><span><b>{r[0]}</b><small>{r[1]}</small></span><em>{r[2]}</em></button>)}</div></Card>
 </div></div>}
function Facilities({facilities,anomalies}){const nav=useNavigate();const[q,setQ]=useState("");const list=facilities.filter(f=>`${f.facility_name} ${f.facility_code} ${f.city}`.toLowerCase().includes(q.toLowerCase()));return <Page title="Facilities" sub="Every connected facility in the FlowSense portfolio"><div className="search wide"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search facilities..."/></div><Card className="table-card"><div className="table-scroll"><table><thead><tr><th>Facility</th><th>Type</th><th>Location</th><th>Status</th><th>Alerts</th><th></th></tr></thead><tbody>{list.map(f=><tr key={f.facility_code}><td><b>{f.facility_name}</b><small>{f.facility_code}</small></td><td>{f.facility_type}</td><td>{f.city}, {f.state}</td><td><span className={`status ${status(f,anomalies).toLowerCase().replaceAll(" ","-")}`}>{status(f,anomalies)}</span></td><td>{anomalies.filter(a=>a.facility_code===f.facility_code).length}</td><td><button className="link" onClick={()=>nav(`/facilities/${f.facility_code}`)}>Open →</button></td></tr>)}</tbody></table></div></Card></Page>}
function Page({title,sub,children}){return <div className="page"><div className="inner"><div className="page-title"><div><div className="overline">FLOWSENSE / OPERATIONS</div><h1>{title}</h1><p>{sub}</p></div></div>{children}</div></div>}
function Resource({type,facilities}){const [selected,setSelected]=useState(facilities[0]?.facility_code||"");const[data,setData]=useState([]);useEffect(()=>{if(!selected)return;api[type](selected,24).then(setData).catch(console.error)},[selected,type]);const isE=type==="energy";return <Page title={isE?"Energy Monitoring":"Water Monitoring"} sub={isE?"Consumption and demand trends":"Flow, input and loss indicators"}><div className="selectbox"><Building2/><select value={selected} onChange={e=>setSelected(e.target.value)}>{facilities.map(f=><option key={f.facility_code} value={f.facility_code}>{f.facility_name}</option>)}</select></div><Card className="large-chart"><div className="panel-head"><div><h2>{isE?"Energy Consumption":"Water Flow"} Trend</h2><p>Last 24 hours · real FastAPI data</p></div></div><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke="#1c2d43"/><XAxis dataKey="reading_time" tickFormatter={fmtTime}/><YAxis/><Tooltip/><Line dataKey="reading_value" stroke={isE?"#31aaff":"#2cc9ed"} dot={false}/></LineChart></ResponsiveContainer></Card></Page>}
function Alerts({anomalies}){const nav=useNavigate();return <Page title="Alerts & Anomalies" sub="Detected abnormal energy, water and equipment conditions"><Card className="table-card"><div className="table-scroll"><table><thead><tr><th>Severity</th><th>Issue</th><th>Facility</th><th>Source</th><th>Deviation</th><th>Detected</th><th></th></tr></thead><tbody>{anomalies.map((a,i)=><tr key={a.anomaly_id||i}><td><span className={`status ${String(a.severity).toLowerCase()}`}>{a.severity}</span></td><td><b>{a.anomaly_type}</b><small>{a.description}</small></td><td>{a.facility_code}</td><td>{a.source_name||a.sensor_name||"IoT"}</td><td>{num(a.deviation_percent)}%</td><td>{new Date(a.detected_at).toLocaleString()}</td><td><button className="link" onClick={()=>nav(`/facilities/${a.facility_code}`)}>Investigate →</button></td></tr>)}</tbody></table></div></Card></Page>}
function Detail({facilities,anomalies}){const{code}=useParams();const f=facilities.find(x=>x.facility_code===code);const[s,setS]=useState(null),[r,setR]=useState([]);useEffect(()=>{if(code){api.summary(code).then(setS).catch(()=>{});api.reconciliation(code,50).then(setR).catch(()=>{})}},[code]);if(!f)return <Page title="Facility Not Found" sub="The selected facility is not available."/>;return <Page title={f.facility_name} sub={`${f.facility_code} · ${f.city}, ${f.state}`}><div className="detail-grid"><Kpi icon={Zap} label="Energy" value={`${num(s?.energy_kwh)} kWh`} sub="Latest sensor value" tone="blue"/><Kpi icon={Droplets} label="Water" value={`${num(s?.water_kl,2)} kL`} sub="Latest sensor value" tone="cyan"/><Kpi icon={AlertTriangle} label="Alerts" value={anomalies.filter(a=>a.facility_code===code).length} sub="Detected events" tone="red"/><Kpi icon={Cpu} label="IoT Device" value={s?.iot_device||"Connected"} sub="Facility device" tone="green"/></div><Card><PanelHead icon={Activity} title="Resource Reconciliation" sub="Main meter vs IoT-observed resource usage"/><div className="table-scroll"><table><thead><tr><th>Resource</th><th>Main Meter</th><th>Observed</th><th>Unaccounted</th><th>%</th><th>Status</th></tr></thead><tbody>{r.slice(0,20).map((x,i)=><tr key={i}><td>{x.resource_type}</td><td>{num(x.main_meter_value)}</td><td>{num(x.observed_iot_value)}</td><td>{num(x.unaccounted_value)}</td><td>{num(x.unaccounted_percent)}%</td><td>{x.status}</td></tr>)}</tbody></table></div></Card></Page>}
function Simple({title,sub,icon:Icon}){return <Page title={title} sub={sub}><Card className="empty big"><Icon/><h2>{title} workspace</h2><p>The navigation route is active and ready for its detailed FlowSense workflow.</p></Card></Page>}
function App(){const[facilities,setFacilities]=useState([]),[anomalies,setAnomalies]=useState([]),[selected,setSelected]=useState("");const load=async()=>{try{const[f,a]=await Promise.all([api.facilities(),api.anomalies(50)]);setFacilities(f);setAnomalies(a);if(!selected&&f[0])setSelected(f[0].facility_code)}catch(e){console.error(e)}};useEffect(()=>{load()},[]);return <BrowserRouter><Shell anomalies={anomalies}><Routes><Route path="/" element={<Overview facilities={facilities} anomalies={anomalies} selected={selected} setSelected={setSelected} onRefresh={load}/>}/><Route path="/facilities" element={<Facilities facilities={facilities} anomalies={anomalies}/>}/><Route path="/facilities/:code" element={<Detail facilities={facilities} anomalies={anomalies}/>}/><Route path="/energy" element={<Resource type="energy" facilities={facilities}/>}/><Route path="/water" element={<Resource type="water" facilities={facilities}/>}/><Route path="/alerts" element={<Alerts anomalies={anomalies}/>}/><Route path="/analytics" element={<Simple title="Analytics" sub="Resource trends, reconciliation and performance" icon={BarChart3}/>}/><Route path="/ai-insights" element={<Simple title="AI Insights" sub="Recommendations and anomaly explanations" icon={Sparkles}/>}/><Route path="/reports" element={<Simple title="Reports" sub="Operational and resource reports" icon={FileText}/>}/><Route path="/devices" element={<Simple title="Devices" sub="IoT device health and connectivity" icon={Cpu}/>}/><Route path="/settings" element={<Simple title="Settings" sub="FlowSense configuration" icon={Settings}/>}/></Routes></Shell></BrowserRouter>}
export default App;
